[package]
name = "nlwkn-rs"
version = "0.1.0"
edition = "2021"
publish = false

[features]
head = []
no-sandbox = []

[[bin]]
name = "cadenza-pdf-fetcher"

[dependencies]
# async runtime
tokio = { version = "1", features = ["full"] }

# headless browser
headless_chrome = { version = "1", features = ["fetch"] }

# reading xlsx
calamine = { version = "0.21", features = ["dates"] }

# data serialization
serde = { version = "1", features = ["derive"] }
serde_with = "3"
serde_json = "1"

# cli
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
console = "0.15"

# utility
const_format = "0.2"
static-toml = "1"
portpicker = "0.1"
lazy_static = "1"

# error handling
anyhow = "1"

# http requests
[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "socks"]

# tor connection
[dependencies.arti]
version = "1"
default-features = false
features = [
    "tokio",
    "compression",
    "rustls",
    "experimental-api",
    "static-sqlite"
]

[dependencies.arti-client]
version = "0.9"
default-features = false
features = [
    "tokio",
    "compression",
    "rustls",
    "experimental",
    "experimental-api",
    "static-sqlite"
]

[dependencies.tor-rtcompat]
version = "0.9"
default-features = false
features = [
    "tokio",
    "rustls"
]
