[cadenza]
root = "http://www.wasserdaten.niedersachsen.de"
url = "http://www.wasserdaten.niedersachsen.de/cadenza/"
retries = 10

[data]
tables = "data/tables"
reports = "data/reports"

[postgres]
database = "wisdom"
